# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tts-0',
                'doc_host': 'https://ahadjawaid.github.io',
                'git_url': 'https://github.com/ahadjawaid/tts-0',
                'lib_path': 'tts_0'},
  'syms': {'tts_0.core': {'tts_0.core.foo': ('core.html#foo', 'tts_0/core.py')}}}
