# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02-hifigan.ipynb.

# %% auto 0
__all__ = ['get_padding']

# %% ../nbs/02-hifigan.ipynb 1
import torch
import torch.nn as nn
from math import sqrt
from typing import Sequence
from torch import Tensor
import torch.nn.functional as F
import fastcore.all as fc

# %% ../nbs/02-hifigan.ipynb 6
def get_padding(ks: int, dilation: int = 1) -> int:
    return ((ks - 1) // 2) * dilation
